### ISSUE TITLE
Error executing nx g @nx-squeezer/workspace:renovate 

### ISSUE THREAD

**Issue by WolfSoko** [nx-squeezer/squeezer#252]
@samuelfernandez great repository that brings a lot of comfort to nx workspaces.

For an existing nx workspace there is an error running: 

`nx g @nx-squeezer/workspace:renovate`

Version used: @nx-squeezer/workspace": "^1.0.1"
Windows11
node v18.12.0
npm v8.19.2

```
>  NX  Generating @nx-squeezer/workspace:renovate

√ Do you want to use Nx Cloud? (Y/n) · true
√ Do you want to use local presets? To have latest updates it is preferred to use the ones provided by @nx-squeezer/squeezer instead of local ones. (y/N) · false
√ Assignee for GitHub PRs · github-user
In order to use Nx Cloud add a secret with the NX_CLOUD_AUTH_TOKEN
It is suggested that you create a new token for this purpose with read/write access.
You can configure it at: https://cloud.nx.app/
Also consider using Nx Cloud GitHub app to access run results: https://github.com/apps/nx-cloud


 >  NX   yaml_1.Scalar is not a constructor

   Pass --verbose to see the stacktrace.

TypeError: yaml_1.Scalar is not a constructor
    at D:\Entwicklung\wol-sok-mono\node_modules\@nx-squeezer\workspace\src\generators\renovate\generator.js:46:30
    at Generator.next (<anonymous>)
    at D:\Entwicklung\wol-sok-mono\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\Entwicklung\wol-sok-mono\node_modules\tslib\tslib.js:114:16)
    at renovateGenerator (D:\Entwicklung\wol-sok-mono\node_modules\@nx-squeezer\workspace\src\generators\renovate\generator.js:13:20)
    at Object.<anonymous> (D:\Entwicklung\wol-sok-mono\node_modules\nx\src\command-line\generate.js:222:36)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Entwicklung\wol-sok-mono\node_modules\tslib\tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

ref: https://github.com/ng-easy/renovate-config/issues/395

**Comment by samuelfernandez** [comment]
@WolfSoko might be a problem with `yaml` dependency. Sorry that it did not work "plug-n-play". Would you please execute this to check the version you are using?

```shell
npm list yaml
```

Do you use legacy peer dependencies?

**Comment by WolfSoko** [comment]
Yes I sadly use legacy-peer-deps. 

Output of: npm list yaml looks error some

```
+-- @angular-devkit/build-angular@15.0.4
| `-- postcss-loader@7.0.1
|   `-- cosmiconfig@7.1.0
|     `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
+-- @nrwl/angular@15.4.2
| `-- @nrwl/webpack@15.4.2
|   +-- css-minimizer-webpack-plugin@3.4.1
|   | `-- cssnano@5.1.14
|   |   `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
|   +-- fork-ts-checker-webpack-plugin@7.2.13
|   | `-- cosmiconfig@7.1.0
|   |   `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
|   `-- postcss-loader@6.2.1
|     `-- cosmiconfig@7.1.0
|       `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
+-- @nrwl/web@15.4.2
| +-- @nrwl/rollup@15.4.2
| | `-- rollup-plugin-postcss@4.0.2
| |   `-- postcss-load-config@3.1.4
| |     `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
| `-- babel-plugin-macros@2.8.0
|   `-- cosmiconfig@6.0.0
|     `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
|     `-- cosmiconfig@7.1.0
|       `-- yaml@1.10.2 deduped invalid: "^2.2.0" from node_modules/@nx-squeezer/workspace
`-- lint-staged@13.1.0
  `-- yaml@2.2.1
```

**Comment by WolfSoko** [comment]
Are you going to release a new Version?
