### ISSUE TITLE
Error when Commiting after running nx g @nx-squeezer/workspace:lint-staged

### ISSUE THREAD

**Issue by WolfSoko** [nx-squeezer/squeezer#255]
Seems like the package is missing: 

Error: Cannot find module "@commitlint/config-conventional" from "repoPath"
    at resolveId (...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\resolve-extends\src\index.ts:131:14)
    at resolveConfig (...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\resolve-extends\src\index.ts:105:20)
    at ...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\resolve-extends\src\index.ts:51:20
    at Array.reduce (<anonymous>)
    at loadExtends (...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\resolve-extends\src\index.ts:49:13)
    at resolveExtends (...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\resolve-extends\src\index.ts:25:19)
    at load (...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\load\src\load.ts:56:33)
    at async main (...\npm-cache\_npx\16d437951fea4b5e\node_modules\@commitlint\cli\src\cli.ts:214:17) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by WolfSoko** [comment]
npm i @commitlint/config-conventional --save-dev did the job

**Comment by WolfSoko** [comment]
Maybe something went wrong installing the deps when running 

nx g @nx-squeezer/workspace:lint-staged

**Comment by WolfSoko** [comment]
Seems like it is a problem with my repo. Will close this for now

**Comment by samuelfernandez** [comment]
Will use `dependencies` instead of `peerDependencies` for legacy compatibility
